modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mods]]
modId="${core_mod_id}"
version="${core_mod_version}"
displayName="${core_mod_name}"
authors="${core_mod_authors}"
description='''${core_mod_description}'''

[[dependencies.${core_mod_id}]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.${core_mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"



